name       : mate-applets
version    : 1.18.0
release    : 5
source     :
    - https://pub.mate-desktop.org/releases/1.18/mate-applets-1.18.0.tar.xz : e0d17215183be290d1243369a3fff87e2a86d0782bea132b7526544f550130d7
license    :
    - GPL-2.0
    - GFDL-1.1
component  : desktop.mate
summary    : Applets for the MATE Desktop
description: |
    Applets for the MATE Desktop
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(upower-glib)
    - itstool
setup      : |
    %configure --with-gtk=3.0 --disable-stickynotes
build      : |
    %make
install    : |
    %make_install
