name       : mate-applets
version    : 1.26.1
release    : 30
source     :
    - https://github.com/mate-desktop/mate-applets/releases/download/v1.26.1/mate-applets-1.26.1.tar.xz : 3ab8f61db376dc333ce4c18722c63a07fab3e8e1272b7e0e097ad4597b17c2c2
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : Applets for the MATE Desktop
description: |
    MATE Desktop panel applets
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(ice)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnl-genl-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - itstool
    - linux-tools-cpupower-devel
    - wireless-tools-devel
    - yelp-tools
setup      : |
    %configure --disable-static \
        --enable-ipv6
build      : |
    %make
install    : |
    %make_install
