name       : mate-applets
version    : 1.20.2
release    : 14
source     :
    - https://pub.mate-desktop.org/releases/1.20/mate-applets-1.20.2.tar.xz : 9a2609dbb3ea4e0bdee67d819c899a6ce7c06f4447be804464fbc2bbba070631
license    :
    - GPL-2.0-only
    - GFDL-1.1-only
component  : desktop.mate
summary    : Applets for the MATE Desktop
description: |
    Applets for the MATE Desktop
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(dbus-python)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(ice)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - itstool
    - linux-tools-cpupower-devel
    - wireless-tools-devel
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
