name       : mate-applets
version    : 1.24.1
release    : 26
source     :
    - https://github.com/mate-desktop/mate-applets/archive/v1.24.1.tar.gz : 659a20eea64d9885c99f367673c4fcdb0578075ca761ad90123225dce5511d07
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : Applets for the MATE Desktop
description: |
    MATE Desktop panel applets
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(ice)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnotify)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - itstool
    - linux-tools-cpupower-devel
    - mate-common
    - wireless-tools-devel
    - yelp-tools
setup      : |
    %autogen --disable-static \
        --enable-ipv6
build      : |
    %make
install    : |
    %make_install
