name       : mate-applets
version    : 1.26.0
release    : 28
source     :
    - https://github.com/mate-desktop/mate-applets/releases/download/v1.26.0/mate-applets-1.26.0.tar.xz : b7e0439b4e0c754233c2988644faa3f6ab6270970061b7a0c635d68d236fc977
license    :
    - GPL-2.0-or-later
    - GFDL-1.1-or-later
component  : desktop.mate
summary    : Applets for the MATE Desktop
description: |
    MATE Desktop panel applets
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtksourceview-3.0)
    - pkgconfig(gucharmap-2.90)
    - pkgconfig(ice)
    - pkgconfig(libgtop-2.0)
    - pkgconfig(libmatepanelapplet-4.0)
    - pkgconfig(libnl-genl-3.0)
    - pkgconfig(libnotify)
    - pkgconfig(libwnck-3.0)
    - pkgconfig(mate-desktop-2.0)
    - pkgconfig(mateweather)
    - pkgconfig(polkit-agent-1)
    - pkgconfig(pygobject-3.0)
    - pkgconfig(sm)
    - pkgconfig(upower-glib)
    - itstool
    - linux-tools-cpupower-devel
    - wireless-tools-devel
    - yelp-tools
setup      : |
    %configure --disable-static \
        --enable-ipv6
build      : |
    %make
install    : |
    %make_install
